artifacts_root : artifacts 
 
data_ingestion :
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/Amaankapadia/DL-project-Dataset/raw/refs/heads/main/Chicken%20fickle%20images.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion 